name: superhorn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.16
  permission_handler: ^11.3.1

  flutter_bluetooth_serial:
    git:
      url: https://github.com/RolandMarton/flutter_bluetooth_serial.git
  device_info_plus: ^11.2.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_native_splash:
  background_image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    image: assets/splash/splash.png
    color: "#FFFFFF"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash/
    - assets/sounds/
    - assets/svg/
    - assets/icons/
    - assets/
    - assets/animation/


  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSansRegular-x3LYV.ttf
          weight: 400
        - asset: assets/fonts/JosefinSansLight-ZVEll.ttf
          weight: 300
        - asset: assets/fonts/JosefinSansBold-OVA7o.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsLight-l4Zw.otf
          weight: 300
        - asset: assets/fonts/PoppinsRegular-B2Bw.otf
          weight: 400
        - asset: assets/fonts/PoppinsBold-GdJA.otf
          weight: 700

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
